# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 30 Jul 2012 06:36:08 +0000
*               @ALL          1
*               @user         8
