<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cmdalbem
 * Date: Sun, 12 Aug 2012 02:29:21 -0300
 */

$conf['title'] = '~cmdalbem';
$conf['start'] = 'home';
$conf['template'] = 'mmclean';
$conf['license'] = 'cc-by-sa';
$conf['tocminheads'] = '10';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['plugin']['maintenancemessage']['maintenance_message_text'] = 'UNDER MAINTENANCE! I\'ll be back shortly :)';
$conf['plugin']['translation']['translations'] = 'pt-br en';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['display'] = 'langcode,name';
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation2']['languages'] = 'pt,en';

// end auto-generated content
